name: Hourly Check
on:
  schedule:
    - cron: "0 * * * *"   # 매시간 정각(UTC)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  hourly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run hourly check
        env:
          MODE: HOURLY_CHECK
          TIMEZONE: Asia/Seoul
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: python main.py
      - name: Commit state if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "ai-tracker-bot"
            git config user.email "actions@users.noreply.github.com"
            git add data/*.json || true
            if ! git diff --cached --quiet; then
              git commit -m "chore(state): hourly seen update"
              git push
            fi
          fi
